"""add language to posts

Revision ID: 125585589f44
Revises: 35c89712322e
Create Date: 2023-12-17 18:01:25.008434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125585589f44'
down_revision = '35c89712322e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
